### ISSUE TITLE
Compilation error (missing test_type) on latest nightlies

### ISSUE THREAD

**Issue by cormacrelf** [commure/datatest#18]
As a result of https://github.com/rust-lang/rust/pull/64873, merged 6 days ago, `rustc_test::TestDesc` now needs a `test_type` field. I'm guessing that will be `TestType:: IntegrationTest`.

```
error[E0063]: missing field `test_type` in initializer of `rustc_test::TestDesc`
   --> /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/datatest-0.5.2/src/runner.rs:171:23
    |
171 |                 desc: TestDesc {
    |                       ^^^^^^^^ missing `test_type`
```

I don't know how this will interact with the whole 'working on stable Rust' goal.

**Comment by idubrov** [comment]
Yeah, it will likely break on next stable, too. The whole "stable" story for datatest is a complete lie at this point.

I was hoping for https://github.com/rust-lang/rust/issues/50297 to make progress, but not clear what's happening there so far.
