### ISSUE TITLE
Support running on stable

### ISSUE THREAD

**Issue by idubrov** [commure/datatest#4]
It's possible to make it run on stable by using [`harness = false`](https://doc.rust-lang.org/cargo/reference/manifest.html#configuring-a-target) in `Cargo.toml`, with the following drawbacks:

1. Extra configuration will be required in `Cargo.toml`.
2. Special macro will be used to provide `main` function. Note that this function will have to be named `main` due to https://github.com/rust-lang/rust/issues/29634 being unstable.
3. In case of binary target (`bin/*` or `main.rs`), extra attribute will be needed on a real main function to disable it when running with tests.
4. Some magic will be needed for registering tests (could use https://crates.io/crates/ctor or https://crates.io/crates/inventory).

Perhaps, can use https://crates.io/crates/libtest crate (which, I think, was pulled from rust itself) to run the tests.

**Comment by idubrov** [comment]
So, the ergonomics will be:

1. Use `harness = false` in `Cargo.toml`
2. Put `#![datatest::test_harness]` attribute at the top of each test / binary. In unstable, it will be possible to use `#![test_runner(datatest::runner)]`.

**Comment by sunshowers** [comment]
Hi @idubrov! Was curious what the status is -- are you working on this at the moment? If not then I or one of my colleagues might jump on this one. We really desire to use datatest on stable Rust :)

**Comment by idubrov** [comment]
No, not really.

I started doing some experiments, but found that getting exactly the same behavior does not seem to be possible in stable, so I abandoned my experiments. Since we are currently very much tied to nightly anyways,  there was no pressure for that 😅

Looking at my notes above, I'm not sure they would work.

1. I think, one issue with `harness = false` was that all regular `#[test]` would be removed by the compiler, which is very unfortunate as I would like to mix regular tests and `#[datatest(..)]` tests. I guess, there could be `datatest::test` attribute instead? But then it is not clear how to "register" all these tests (it seems like compiler generates some plumbing to accumulate all of these tests into a `Vec` of `TestDescAndFn`
2. ctor/inventory might also not work due to https://github.com/dtolnay/inventory/issues/7

The alternative would be to abandon current ergonomics and simply generate one single test which would loop over set of tests internally. However, that would be a pretty big deal for me -- the main advantage currently is that each test case behaves like a separate `#[test]` from the point of view of `cargo test` / IntelliJ plugins.

Though, I guess it could be done based on Rust detection nightly vs stable.

I was also hoping for some progress on https://github.com/rust-lang/rust/issues/50297, but it doesn't move anywhere it seems.

**Comment by sunshowers** [comment]
Thanks for the detailed notes!

In our case 1 is not a huge issue as our datatests are not mixed with regular ones but I totally see what you mean. Curious, would you be ok with that limitation on stable only?

2 is really unfortunate :(

Yeah, I agree that having a separate test per data file is essential.

**Comment by idubrov** [comment]
>Curious, would you be ok with that limitation on stable only?

Yeah, sure.

**Comment by idubrov** [comment]
Okay, I've done my first stab at supporting stable: #8. Still does not support standard tests, but otherwise seems like it works (with few caveats)?

**Comment by idubrov** [comment]
I would call it done-ish, seems to work on stable now. Differences from nightly usage:

1. Set `harness = false` for your test. If you don't, all tests will be silently ignored 🙀, maybe, I can use `#[ctor::dtor]` to check if test runner was actually called.
2. Use `datatest::harness!();` in the test file. Otherwise, it will fail to run.
3. Add `use datatest::test;` everywhere you use regular `#[test]`. If you don't, regular tests will be silently ignored 🥶. Not sure if I can add any kind of protection here, with `harness = false` rustc simply discards all the `#[test]`, it seems...  🤔

**Comment by sunshowers** [comment]
Thank you for your work!

I tried using it and ran into the following issue. It's possible this got masked for you when you set `RUSTC_BOOTSTRAP` in `build.rs` -- it might make sense to extract the `datatest_stable` test into another crate to be sure.

```
error[E0658]: use of unstable library feature 'custom_test_frameworks': custom test frameworks are an unstable feature
  --> testsuite/libra_fuzzer/tests/artifacts.rs:19:1
   |
19 | / #[datatest::files("artifacts", {
20 | |     artifact_path in r"^.*/.*"
21 | | })]
   | |___^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/50297
   = help: add #![feature(custom_test_frameworks)] to the crate attributes to ena
ble
```

**Comment by idubrov** [comment]
I think, this happens if you run it on nightly BUT don't enable `#![feature(custom_test_frameworks)]`. Currently it tries to detect which version it runs on by using `version_check` (https://github.com/commure/datatest/blob/master/build.rs#L4-L9) and then it either uses nightly-only `#[test_case]` or uses `ctor`-based registry for stable.

It's a bit of a mess right now :(

**Comment by sunshowers** [comment]
Ahh I see, yeah that's exactly what I was trying to do! OK, good to know that it'll work better on stable Rust, I'll give that a shot.

BTW there has been some noise about forbidding `RUSTC_BOOTSTRAP` in build scripts uploaded to crates.io: https://github.com/rust-lang/cargo/pull/6608

**Comment by nox** [comment]
> BTW there has been some noise about forbidding `RUSTC_BOOTSTRAP` in build scripts uploaded to crates.io: [rust-lang/cargo#6608](https://github.com/rust-lang/cargo/pull/6608)

Please don't use `RUSTC_BOOTSTRAP`, you are not bootstrapping the compiler.

**Comment by sunshowers** [comment]
With all due respect, @nox, as much as I agree with your object-level position — your comment (and the general style of your comments across these discussions) is phrased very unhelpfully. I've worked on developer tooling for many years, and one thing I've learned is that tools are for people to solve problems. If people are using the tool in unintended ways, the problem lies with the tool, not with the people. This is indeed one of the reasons Rust is so successful — it tries to be as accessible as possible instead of blaming its users for making mistakes.

At the very least it's worth understanding your users and trying to help them achieve their goals through other means. For example, in this case a test library available on crates.io wasn't used because it seemed to be too old. Maybe it's worth publishing a newer version of that library?

Thank you!

**Comment by nox** [comment]
> This is indeed one of the reasons Rust is so successful — it tries to be as accessible as possible instead of blaming its users for making mistakes.

One of the biggest reasons Rust succeeded is that people can rely heavily on its stability promise that crates that work on stable will do so indefinitely (barring critical bugs). Using `RUSTC_BOOTSTRAP` through the build script to silently enable unstable features breaks this promise.
